SELECT * FROM pizza_sales;
SELECT SUM ( TOTAL_PRICE)AS TOTAL_REVENUE FROM pizza_sales;
SELECT CAST(SUM(TOTAL_PRICE)AS DECIMAL(10,2))AS TOTAL_REVENUE FROM pizza_sales;
SELECT SUM(TOTAL_PRICE) /(COUNT(DISTINCT ORDER_ID))from pizza_sales;
